### ISSUE TITLE
brew install guumaster/tap/hostctl  does not work on Apple M1

### ISSUE THREAD

**Issue by yaohuangguan** [guumaster/hostctl#75]
Error: Invalid formula: /opt/homebrew/Library/Taps/guumaster/homebrew-tap/hostctl.rb
formulae require at least a URL
Error: Cannot tap guumaster/tap: invalid syntax in tap!

**Comment by guumaster** [comment]
Hi @yaohuangguan thanks for reporting this. The publication as a homebrew formula is handled by `goreleaser`.

It looks like this is a `goreleaser` issue only addressing `CPU.intel`. 

The formulae is updated with the latest release here: https://github.com/guumaster/homebrew-tap/blob/master/hostctl.rb.

I'll check on `goreleaser` docs/issues to see if they've addressed this.

**Comment by yaohuangguan** [comment]
what should i do in this case to work properly?

**Comment by guumaster** [comment]
@yaohuangguan actually this is an issue with the tool to release versions, so no much you can do unless you know something about `goreleaser`. It'll take some days until I get time to investigate further.

In the meantime, you can try the binary that are generated here: https://github.com/guumaster/hostctl/releases/tag/v1.1.0

**Comment by Fontinalis** [comment]
@guumaster The above mentioned command does not work, but the binary does! Thanks for the fix and great work on this project! 👍🏻

**Comment by frob** [comment]
I added a PR to the guumaster/homebrew-tap repo that will add the ARM release to macos. This should make hostctl installable with homebrew on M1 macs.

**Comment by guumaster** [comment]
I've merged it, but I'm afraid that file is automatically updated by `go-releaser` GitHub action though

**Comment by abarani** [comment]
Just want to chime in to say that the current macOS release still does not work on Apple Silicon without Rosetta installed.

Apple Silicon support has only landed in Go 1.16: https://go.dev/doc/go1.16#darwin
Bumping Go version to 1.16 from the current 1.14 should build a correct darwin arm64 binary file.
